export const BACKEND_URL = "https://seismic-backend-04272025-bjbxatgnadguabg9.centralus-01.azurewebsites.net/"
// export const BACKEND_URL = "http://localhost:8080"
export const DOCTOR_PORTAL_URL = "https://patient-dev.seismicconnect.com/"
export const SOS_URL = "https://seismicdockerbackend-fthfbxbscbcwe3hr.centralus-01.azurewebsites.net/"
export const POWERBI_API_BASE_URL = "https://seismicdockerbackend-fthfbxbscbcwe3hr.centralus-01.azurewebsites.net/"
export const STREAM_API_KEY = "72499ykcfb3z"
export const REDIRECT_URI = "http://localhost:3000/"
// export const REDIRECT_URI = "https://dev.seismicconnect.com/"
// export const CHATBOT_URL = "https://chat-strlit-gva3h7ekahgdctgk.centralus-01.azurewebsites.net";
export const CHATBOT_URL = "https://nova-str-test-fafhb6eda6hmg7du.centralus-01.azurewebsites.net/chat_embed";
